### PR TITLE
Adds extension info and tests for GraphQL compiler

### PR DESCRIPTION
**Pull request by wasd171**
Hello.

This PR adds support for `.graphql` files to `electron-compile`.

### CODE REVIEW

**Comment by paulcbetts** [comment]
Refs https://github.com/electron/electron-compilers/pull/68

**Comment by paulcbetts** [comment]
Great PR! I fixed up a few small things but it's looking good

**Comment by wasd171** [comment]
Thank you! I can change it if needed, tests structure was a bit complicated. Would you mind publishing updated version on npm?

**Comment by paulcbetts** [comment]
Already done, electron-compile 6.4.0 is you, make sure to upgrade -compilers too

**Comment by wasd171** [comment]
Great!

**Pull request merged**
